[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
avian3d = { workspace = true }
lightyear = { workspace = true }

directories = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

thiserror = { workspace = true }
